### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XDqrkneZ** [Chris-Prime/xCrate#2]
00:59:18 [INFO] Enabling xCrate v1.0.0
00:59:18 [CRITICAL] TypeError: "Argument 2 passed to pocketmine\utils\Config::load() must be of the type integer, array given, called in /root/lol/src/pocketmine/utils/Config.php on line 85" (EXCEPTION) in "/src/pocketmine/utils/Config" at line 117
00:59:18 [INFO] Disabling xCrate v1.0.0
00:59:18 [CRITICAL] TypeError: "Argument 2 passed to pocketmine\utils\Config::load() must be of the type integer, array given, called in /root/lol/src/pocketmine/utils/Config.php on line 85" (EXCEPTION) in "/src/pocketmine/utils/Config" at line 117

**Comment by winterbuild7074** [comment]
The creator didn't finish this plugin.

**Comment by Chris-Prime** [comment]
Exactly
